/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gewebe_CGALBooleanOperations3 */

#ifndef _Included_gewebe_CGALBooleanOperations3
#define _Included_gewebe_CGALBooleanOperations3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gewebe_CGALBooleanOperations3
 * Method:    boolean_operation
 * Signature: (I[F[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_gewebe_CGALBooleanOperations3_boolean_1operation
  (JNIEnv *, jobject, jint, jfloatArray, jfloatArray);

/*
 * Class:     gewebe_CGALBooleanOperations3
 * Method:    version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gewebe_CGALBooleanOperations3_version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
