/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hfkbremen_gewebe_CGALAlphaShape3 */

#ifndef _Included_de_hfkbremen_gewebe_CGALAlphaShape3
#define _Included_de_hfkbremen_gewebe_CGALAlphaShape3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hfkbremen_gewebe_CGALAlphaShape3
 * Method:    version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_hfkbremen_gewebe_CGALAlphaShape3_version
  (JNIEnv *, jobject);

/*
 * Class:     de_hfkbremen_gewebe_CGALAlphaShape3
 * Method:    init_alpha_shape
 * Signature: ([F)J
 */
JNIEXPORT jlong JNICALL Java_de_hfkbremen_gewebe_CGALAlphaShape3_init_1alpha_1shape
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     de_hfkbremen_gewebe_CGALAlphaShape3
 * Method:    get_alpha_shape_facets
 * Signature: (Ljava/lang/String;FJ)[I
 */
JNIEXPORT jintArray JNICALL Java_de_hfkbremen_gewebe_CGALAlphaShape3_get_1alpha_1shape_1facets
  (JNIEnv *, jobject, jstring, jfloat, jlong);

/*
 * Class:     de_hfkbremen_gewebe_CGALAlphaShape3
 * Method:    get_alpha_shape_facets_optimal
 * Signature: (Ljava/lang/String;IJ)[I
 */
JNIEXPORT jintArray JNICALL Java_de_hfkbremen_gewebe_CGALAlphaShape3_get_1alpha_1shape_1facets_1optimal
  (JNIEnv *, jobject, jstring, jint, jlong);

/*
 * Class:     de_hfkbremen_gewebe_CGALAlphaShape3
 * Method:    get_alpha
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_de_hfkbremen_gewebe_CGALAlphaShape3_get_1alpha
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_hfkbremen_gewebe_CGALAlphaShape3
 * Method:    number_of_solid_components
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_hfkbremen_gewebe_CGALAlphaShape3_number_1of_1solid_1components
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_hfkbremen_gewebe_CGALAlphaShape3
 * Method:    get_alpha_shape_mesh
 * Signature: (Ljava/lang/String;FJ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_de_hfkbremen_gewebe_CGALAlphaShape3_get_1alpha_1shape_1mesh
  (JNIEnv *, jobject, jstring, jfloat, jlong);

/*
 * Class:     de_hfkbremen_gewebe_CGALAlphaShape3
 * Method:    get_optimal_alpha
 * Signature: (IJ)F
 */
JNIEXPORT jfloat JNICALL Java_de_hfkbremen_gewebe_CGALAlphaShape3_get_1optimal_1alpha
  (JNIEnv *, jobject, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
