/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hfkbremen_gewebe_CGALBooleanOperations3 */

#ifndef _Included_de_hfkbremen_gewebe_CGALBooleanOperations3
#define _Included_de_hfkbremen_gewebe_CGALBooleanOperations3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hfkbremen_gewebe_CGALBooleanOperations3
 * Method:    boolean_operation
 * Signature: (I[F[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_de_hfkbremen_gewebe_CGALBooleanOperations3_boolean_1operation
  (JNIEnv *, jobject, jint, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
