/*
 * Gewebe
 *
 * This file is part of the *wellen* library (https://github.com/dennisppaul/wellen).
 * Copyright (c) 2024 Dennis P Paul.
 *
 * This library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package gewebe;

public class OBJTetrahedron {

    public static final String[] DATA = {
            "# WaveFront *.obj file (generated by Cinema 4D)",
            "",
            "v 81.649658203125 -33.33333206176758 -47.14045333862305",
            "v -81.649658203125 -33.33333206176758 -47.14045333862305",
            "v 0 -33.33333206176758 94.28090667724609",
            "v 0 100 0",
            "# 4 vertices",
            "",
            "vn 0 -1 0",
            "vn 0 -1 0",
            "vn 0 -1 0",
            "vn 0 0.33333334326744 -0.94280898571014",
            "vn 0 0.33333334326744 -0.94280898571014",
            "vn 0 0.33333334326744 -0.94280898571014",
            "vn -0.81649655103683 0.33333337306976 0.47140455245972",
            "vn -0.81649655103683 0.33333337306976 0.47140455245972",
            "vn -0.81649655103683 0.33333337306976 0.47140455245972",
            "vn 0.81649655103683 0.33333337306976 0.47140455245972",
            "vn 0.81649655103683 0.33333337306976 0.47140455245972",
            "vn 0.81649655103683 0.33333337306976 0.47140455245972",
            "# 12 normals",
            "",
            "vt 0 0.5 0",
            "vt 0 1 0",
            "vt 0.43299996852875 0.75 0",
            "vt 0 1 0",
            "vt 0 0.5 0",
            "vt 0.43299996852875 0.25 0",
            "vt 0 0 0",
            "vt 0 1 0",
            "vt 0.86599999666214 0.5 0",
            "vt 0.43299996852875 0.25 0",
            "vt 0.43299996852875 0.75 0",
            "vt 0 1 0",
            "vt 0.43299996852875 0.75 0",
            "vt 0.43299996852875 0.25 0",
            "vt 0 0.5 0",
            "vt 0 1 0",
            "# 16 texture coordinates",
            "",
            "g Platonischer_Körper",
            "usemtl default",
            "f 3/3/1 2/2/1 1/1/1",
            "f 2/7/4 4/6/4 1/1/4",
            "f 3/3/7 4/6/7 2/9/7",
            "f 1/1/10 4/6/10 3/3/10",
            "",
            };
}
